version: '3'
services:
  service_orbslam2:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: orbslam2_container
    stdin_open: true
    tty: true
    privileged: true
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - DISPLAY=${DISPLAY}
    command: ["bash"]
    volumes:
      - /dev/shm:/dev/shm
      - ../:/home/user/code
      # - /media/olivier_g/T7_Shield4/ICRA2024_OG/dataset:/home/user/data
      - ../../data_test:/home/user/data_examples
      - /media/jean-michel/SSD_JM1/OG:/home/user/data
      - /tmp/.X11-unix:/tmp/.X11-unix
      # - ../../data_test/:/home/user/data
      # - <Add directory dataset>:/home/user/code/dataset_mount_point/ #Mount directory to dataset
  
