version: '3'
services:
  service_orbslam2:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: orbslam2_container
    stdin_open: true
    tty: true
    privileged: true
    network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY}
    command: ["bash"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    volumes:
      - /dev/shm:/dev/shm
      - ../:/home/user/code
      - ../../data/:/home/user/code/data
      # - <Add directory dataset>:/home/user/code/dataset_mount_point/ #Mount directory to dataset
  
